//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Business.ExternalContributionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponseOfboolean", Namespace="http://schemas.datacontract.org/2004/07/Etsi.Contribution.WCF.Interface")]
    [System.SerializableAttribute()]
    public partial class ServiceResponseOfboolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Etsi.Ultimate.Business.ExternalContributionService.ServiceReport ReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Etsi.Ultimate.Business.ExternalContributionService.ServiceReport Report {
            get {
                return this.ReportField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportField, value) != true)) {
                    this.ReportField = value;
                    this.RaisePropertyChanged("Report");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceReport", Namespace="http://schemas.datacontract.org/2004/07/Etsi.Contribution.WCF.Interface")]
    [System.SerializableAttribute()]
    public partial class ServiceReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] InfoListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] WarningListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ErrorList {
            get {
                return this.ErrorListField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorListField, value) != true)) {
                    this.ErrorListField = value;
                    this.RaisePropertyChanged("ErrorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] InfoList {
            get {
                return this.InfoListField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoListField, value) != true)) {
                    this.InfoListField = value;
                    this.RaisePropertyChanged("InfoList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] WarningList {
            get {
                return this.WarningListField;
            }
            set {
                if ((object.ReferenceEquals(this.WarningListField, value) != true)) {
                    this.WarningListField = value;
                    this.RaisePropertyChanged("WarningList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExternalContributionService.IExtContributionService")]
    public interface IExtContributionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtContributionService/GenerateMeetingTdocListsAsynchronously" +
            "", ReplyAction="http://tempuri.org/IExtContributionService/GenerateMeetingTdocListsAsynchronously" +
            "Response")]
        Etsi.Ultimate.Business.ExternalContributionService.ServiceResponseOfboolean GenerateMeetingTdocListsAsynchronously(string[] uids, int personId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtContributionService/GenerateMeetingTdocListsAsynchronously" +
            "", ReplyAction="http://tempuri.org/IExtContributionService/GenerateMeetingTdocListsAsynchronously" +
            "Response")]
        System.Threading.Tasks.Task<Etsi.Ultimate.Business.ExternalContributionService.ServiceResponseOfboolean> GenerateMeetingTdocListsAsynchronouslyAsync(string[] uids, int personId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExtContributionServiceChannel : Etsi.Ultimate.Business.ExternalContributionService.IExtContributionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExtContributionServiceClient : System.ServiceModel.ClientBase<Etsi.Ultimate.Business.ExternalContributionService.IExtContributionService>, Etsi.Ultimate.Business.ExternalContributionService.IExtContributionService {
        
        public ExtContributionServiceClient() {
        }
        
        public ExtContributionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExtContributionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExtContributionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExtContributionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Etsi.Ultimate.Business.ExternalContributionService.ServiceResponseOfboolean GenerateMeetingTdocListsAsynchronously(string[] uids, int personId) {
            return base.Channel.GenerateMeetingTdocListsAsynchronously(uids, personId);
        }
        
        public System.Threading.Tasks.Task<Etsi.Ultimate.Business.ExternalContributionService.ServiceResponseOfboolean> GenerateMeetingTdocListsAsynchronouslyAsync(string[] uids, int personId) {
            return base.Channel.GenerateMeetingTdocListsAsynchronouslyAsync(uids, personId);
        }
    }
}
