//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2003_06_25_schedule_essentials_table
    {
        public string spec { get; set; }
        public string release { get; set; }
        public Nullable<int> Vx { get; set; }
        public Nullable<int> Vy { get; set; }
        public Nullable<int> Vz { get; set; }
        public Nullable<System.DateTime> available { get; set; }
        public Nullable<bool> withdrawn { get; set; }
        public string Version_remarks { get; set; }
        public string URL { get; set; }
        public int Row_id { get; set; }
    }
}
