//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2001_04_25_schedule
    {
        public string spec { get; set; }
        public string release { get; set; }
        public Nullable<double> SCHED_POSITION { get; set; }
        public string MLS_NAME { get; set; }
        public Nullable<System.DateTime> TARGET_DATE { get; set; }
        public Nullable<System.DateTime> ACHIEVED_DATE { get; set; }
        public Nullable<int> MAJOR_VERSION_NB { get; set; }
        public Nullable<int> TECHNICAL_VERSION_NB { get; set; }
        public Nullable<int> EDITORIAL_VERSION_NB { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> MOD_TS { get; set; }
        public string MOD_BY { get; set; }
        public Nullable<System.DateTime> expert_provided { get; set; }
        public string mcc_remarks { get; set; }
        public string location { get; set; }
        public Nullable<int> WKI_ID { get; set; }
        public Nullable<bool> suppress_SDO_publication { get; set; }
        public Nullable<bool> suppress_from_missing__list { get; set; }
        public string meeting { get; set; }
        public Nullable<bool> Q1741_3 { get; set; }
        public Nullable<bool> force_publication { get; set; }
        public Nullable<bool> M1457 { get; set; }
        public Nullable<System.DateTime> proof { get; set; }
        public Nullable<System.DateTime> uploaded { get; set; }
        public Nullable<System.DateTime> toETSI { get; set; }
        public Nullable<System.DateTime> completed { get; set; }
        public Nullable<bool> multifile { get; set; }
        public int Row_id { get; set; }
    }
}
