//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2004_01_15_WID_history
    {
        public Nullable<int> uid { get; set; }
        public string tdoc { get; set; }
        public Nullable<System.DateTime> when_added { get; set; }
        public int Row_id { get; set; }
    }
}
