//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2005_06_15_TSGs
    {
        public Nullable<int> id { get; set; }
        public string TSG_name { get; set; }
        public string TSG_code_letter { get; set; }
        public int Row_id { get; set; }
    }
}
