//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2006_03_17_tdocs
    {
        public Nullable<int> doc_mtgId { get; set; }
        public string doc_mtg { get; set; }
        public string doc_tdoc { get; set; }
        public string doc_title { get; set; }
        public string doc_source { get; set; }
        public string doc_remarks { get; set; }
        public string doc_hlink { get; set; }
        public Nullable<System.DateTime> record_added { get; set; }
        public Nullable<System.DateTime> url_checked { get; set; }
        public Nullable<System.DateTime> title_source_checked { get; set; }
        public Nullable<System.DateTime> crHarvested { get; set; }
        public Nullable<bool> crFlag { get; set; }
        public int Row_id { get; set; }
        public Nullable<bool> badURL { get; set; }
    }
}
