//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2003_03_04_work_plan
    {
        public Nullable<double> ID { get; set; }
        public Nullable<double> Unique_ID { get; set; }
        public string Task_Name { get; set; }
        public string Acronym { get; set; }
        public Nullable<double> Outline_Level { get; set; }
        public string Release { get; set; }
        public string Resource_Names { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> Finish { get; set; }
        public Nullable<double> C__Work_Complete { get; set; }
        public string HyPerlink { get; set; }
        public string WI_rapporteur_name { get; set; }
        public Nullable<System.DateTime> last_modif { get; set; }
        public string Notes { get; set; }
        public string Stopped_at { get; set; }
        public string Early { get; set; }
        public Nullable<double> rappid { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string Level_of_Approval { get; set; }
        public string Impacted_TSs_and_TRs { get; set; }
        public string TSG_approved { get; set; }
        public string PCG_approved { get; set; }
        public string Status_Report { get; set; }
        public Nullable<double> L1uid { get; set; }
        public Nullable<double> L2uid { get; set; }
        public Nullable<double> L3uid { get; set; }
        public Nullable<double> L4uid { get; set; }
        public Nullable<double> parent_uid { get; set; }
        public int Row_id { get; set; }
    }
}
