//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2002_08_06_CR_implementation_errors
    {
        public Nullable<System.Guid> CR_record_key { get; set; }
        public string Spec { get; set; }
        public string CR { get; set; }
        public string Rev { get; set; }
        public Nullable<System.DateTime> Time_of_report { get; set; }
        public string Reason_of_Error { get; set; }
        public string Remarks { get; set; }
        public int Row_id { get; set; }
    }
}
