//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2002_04_25_WPM_title_lines
    {
        public Nullable<bool> LTE { get; set; }
        public Nullable<bool> C3g { get; set; }
        public Nullable<bool> C2g { get; set; }
        public string title_1_part { get; set; }
        public int Row_id { get; set; }
    }
}
