//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2009_06_11_CRs_to_WIs
    {
        public string wicode { get; set; }
        public string wispec { get; set; }
        public string wicr { get; set; }
        public string wicrrev { get; set; }
        public int Row_id { get; set; }
        public string wicrsubj { get; set; }
    }
}
