//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2003_06_25_schedule_essentials_table
    {
        public string spec { get; set; }
        public string release { get; set; }
        public Nullable<int> Vx { get; set; }
        public Nullable<int> Vy { get; set; }
        public Nullable<int> Vz { get; set; }
        public Nullable<System.DateTime> available { get; set; }
        public Nullable<bool> withdrawn { get; set; }
        public string Version_remarks { get; set; }
        public string URL { get; set; }
        public int Row_id { get; set; }
    }
}
