//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2010_02_08_SpecXRef
    {
        public string referenceSpecReferencing { get; set; }
        public string referenceSpecReferenced { get; set; }
        public string referenceRel { get; set; }
        public Nullable<bool> referenceSpecRfedWdrwn { get; set; }
        public Nullable<bool> referenceSpecRfedWdrwnRel { get; set; }
        public Nullable<System.DateTime> referenceAdded { get; set; }
        public Nullable<bool> referenceOked { get; set; }
        public int Row_id { get; set; }
    }
}
