//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2010_02_08_SpecXRef
    {
        public string referenceSpecReferencing { get; set; }
        public string referenceSpecReferenced { get; set; }
        public string referenceRel { get; set; }
        public Nullable<bool> referenceSpecRfedWdrwn { get; set; }
        public Nullable<bool> referenceSpecRfedWdrwnRel { get; set; }
        public Nullable<System.DateTime> referenceAdded { get; set; }
        public Nullable<bool> referenceOked { get; set; }
        public int Row_id { get; set; }
    }
}
