//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmtee_officers
    {
        public Nullable<int> TB_ID { get; set; }
        public Nullable<int> PERSON_ID { get; set; }
        public string role { get; set; }
        public Nullable<System.DateTime> elected_on { get; set; }
        public int Row_id { get; set; }
    }
}
