//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class committee
    {
        public Nullable<int> TB_ID { get; set; }
        public string TB_KEY1 { get; set; }
        public string TB_KEY2 { get; set; }
        public string TB_KEY3 { get; set; }
        public string TB_TITLE { get; set; }
        public Nullable<int> PARENT_TB_ID { get; set; }
        public string WKIREF_PREFIX { get; set; }
        public string TB_NAME { get; set; }
        public string TB_STATUS { get; set; }
        public int Row_id { get; set; }
    }
}
