//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class committee
    {
        public Nullable<int> TB_ID { get; set; }
        public string TB_KEY1 { get; set; }
        public string TB_KEY2 { get; set; }
        public string TB_KEY3 { get; set; }
        public string TB_TITLE { get; set; }
        public Nullable<int> PARENT_TB_ID { get; set; }
        public string WKIREF_PREFIX { get; set; }
        public string TB_NAME { get; set; }
        public string TB_STATUS { get; set; }
        public int Row_id { get; set; }
    }
}
