//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_categories
    {
        public string CR_category { get; set; }
        public string meaning { get; set; }
        public int Row_id { get; set; }
    }
}
