//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_status_values
    {
        public string CR_status_value { get; set; }
        public Nullable<int> sort_order { get; set; }
        public Nullable<bool> TSG { get; set; }
        public Nullable<bool> WG { get; set; }
        public string use { get; set; }
        public int Row_id { get; set; }
    }
}
