//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_status_values
    {
        public string CR_status_value { get; set; }
        public Nullable<int> sort_order { get; set; }
        public Nullable<bool> TSG { get; set; }
        public Nullable<bool> WG { get; set; }
        public string use { get; set; }
        public int Row_id { get; set; }
    }
}
