//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class jmm_spec_series
    {
        public string series_id { get; set; }
        public string series_description { get; set; }
        public Nullable<bool> series_3g { get; set; }
        public Nullable<bool> series_2g { get; set; }
        public int Row_id { get; set; }
    }
}
