//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class jmm_spec_series
    {
        public string series_id { get; set; }
        public string series_description { get; set; }
        public Nullable<bool> series_3g { get; set; }
        public Nullable<bool> series_2g { get; set; }
        public int Row_id { get; set; }
    }
}
