//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_of_GSM___3G_CRs
    {
        public string Meeting_1st_Level { get; set; }
        public string Doc_1st_Level { get; set; }
        public string Status_1st_Level { get; set; }
        public string Spec { get; set; }
        public string CR { get; set; }
        public string Rev { get; set; }
        public string Phase { get; set; }
        public string Subject { get; set; }
        public string Cat { get; set; }
        public string Version_Current { get; set; }
        public string Version_New { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Source_1st_Level { get; set; }
        public string WG_Responsible { get; set; }
        public string Meeting_2nd_Level { get; set; }
        public string Doc_2nd_Level { get; set; }
        public string Status_2nd_Level { get; set; }
        public string Workitem { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string Source_2nd_Level { get; set; }
        public int Row_id { get; set; }
    }
}
