//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LSs_importedSnapshot
    {
        public Nullable<int> id { get; set; }
        public string Tdoc { get; set; }
        public string source_cmtee { get; set; }
        public string source_mtg { get; set; }
        public string destination_cmtee { get; set; }
        public string destination_meeting { get; set; }
        public string cc_cmtee { get; set; }
        public string cc_meeting { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> date_at_coord { get; set; }
        public string treated_at_mtg { get; set; }
        public Nullable<bool> done { get; set; }
        public int Row_id { get; set; }
    }
}
