//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class plenary_meetings_with_end_dates
    {
        public string meeting { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> target { get; set; }
        public Nullable<System.DateTime> dealine_090pc { get; set; }
        public Nullable<System.DateTime> dealine_100pc { get; set; }
        public string meeting_directory { get; set; }
        public string specs_directory { get; set; }
        public string min_doc_nbr { get; set; }
        public string max_doc_nbr { get; set; }
        public string tdocs_directory { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<int> mtg_id { get; set; }
        public string location { get; set; }
        public string body { get; set; }
        public Nullable<int> tb_id { get; set; }
        public Nullable<System.DateTime> record_created { get; set; }
        public string locCountry { get; set; }
        public string UTCoffset { get; set; }
        public string title { get; set; }
        public Nullable<bool> suppress { get; set; }
        public string dosPath { get; set; }
        public Nullable<System.DateTime> tdoclist { get; set; }
        public string satisfactionURL { get; set; }
        public Nullable<int> ItSupportPerson { get; set; }
        public Nullable<int> colloc_mtg_id { get; set; }
        public int Row_id { get; set; }
    }
}
