//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specs_GSM_3G_release_info
    {
        public string Spec { get; set; }
        public string Release { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> withdrawn { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> wpm_record_id { get; set; }
        public string freeze_meeting { get; set; }
        public string stopped_at_meeting { get; set; }
        public Nullable<bool> inhibitUpgrade { get; set; }
        public int Row_id { get; set; }
    }
}
