//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specs_GSM_3G_release_info
    {
        public string Spec { get; set; }
        public string Release { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> withdrawn { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> wpm_record_id { get; set; }
        public string freeze_meeting { get; set; }
        public string stopped_at_meeting { get; set; }
        public Nullable<bool> inhibitUpgrade { get; set; }
        public int Row_id { get; set; }
    }
}
