//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Tools.TmpDbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specs_GSM_3G
    {
        public string Type { get; set; }
        public string Number { get; set; }
        public Nullable<bool> For_publication { get; set; }
        public string Title { get; set; }
        public string former_WG { get; set; }
        public string WG_prime { get; set; }
        public string WG_other { get; set; }
        public Nullable<int> rapporteur_id { get; set; }
        public string general_remarks { get; set; }
        public Nullable<bool> C2g { get; set; }
        public Nullable<bool> C3g { get; set; }
        public string txfer_to_3GPP_notes { get; set; }
        public string transferred_to_3GPP { get; set; }
        public Nullable<bool> C2g_common { get; set; }
        public Nullable<bool> definitively_withdrawn { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<System.DateTime> title_verified { get; set; }
        public string URL { get; set; }
        public Nullable<bool> Q1741_2 { get; set; }
        public Nullable<bool> M1457 { get; set; }
        public Nullable<int> WI_UID { get; set; }
        public string description { get; set; }
        public Nullable<bool> LTE { get; set; }
        public Nullable<bool> ComIMS { get; set; }
        public Nullable<bool> EPS { get; set; }
        public Nullable<bool> rapporteurChairman { get; set; }
        public Nullable<bool> otherAx { get; set; }
        public Nullable<int> MCC_id { get; set; }
        public int Row_id { get; set; }
    }
}
