CREATE TABLE [dbo].[WorkItems](
	[Pk_WorkItemUid] [int] NOT NULL,
	[WorkplanId] [int] NULL,
	[Name] [varchar](255) NULL,
	[Acronym] [varchar](50) NULL,
	[WiLevel] [int] NULL,
	[StartDate] [datetime] NULL,
	[EndDate] [datetime] NULL,
	[Completion] [int] NULL,
	[LastModification] [datetime] NULL,
	[CreationDate] [datetime] NULL,
	[Fk_ParentWiId] [int] NULL,
	[Fk_ReleaseId] [int] NULL,
	[Wid] [varchar](20) NULL,
	[RapporteurId] [int] NULL,
	[RapporteurStr] [varchar](100) NULL,
	[TsgApprovalMtgId] [int] NULL,
	[TsgApprovalMtgRef] [varchar](20) NULL,
	[PcgApprovalMtgId] [int] NULL,
	[PcgApprovalMtgRef] [varchar](20) NULL,
	[TsgStoppedMtgId] [int] NULL,
	[TsgStoppedMtgRef] [varchar](20) NULL,
	[PcgStoppedMtgId] [int] NULL,
	[PcgStoppedMtgRef] [varchar](20) NULL,
	[StatusReport] [varchar](50) NULL,
	[RapporteurCompany] [varchar](100) NULL,
	[TssAndTrs] [varchar](50) NULL,
    CONSTRAINT [PK_WorkItems] PRIMARY KEY CLUSTERED ([Pk_WorkItemUid] ASC),
    CONSTRAINT [FK_WorkItems_ParentWi] FOREIGN KEY ([Fk_ParentWiId]) REFERENCES [dbo].[WorkItems] ([Pk_WorkItemUid]),
    CONSTRAINT [FK_WorkItems_Releases] FOREIGN KEY ([Fk_ReleaseId]) REFERENCES [dbo].[Releases] ([Pk_ReleaseId])
);

