USE [TMP3GPPDB]

SET NOCOUNT ON

DECLARE @CURRENT_TABLE_NAME nvarchar(100)
DECLARE @CMD nvarchar(4000)
DECLARE @LIST_TABLES TABLE
(
	TABLE_NAME nvarchar(100)
)

--list of tables to import
INSERT INTO @LIST_TABLES VALUES ('2001-04-25_schedule')
INSERT INTO @LIST_TABLES VALUES ('2001-11-06_filius-patris')
INSERT INTO @LIST_TABLES VALUES ('2002-04-25_WPM-title-lines')
INSERT INTO @LIST_TABLES VALUES ('2002-08-06_CR-implementation-errors')
INSERT INTO @LIST_TABLES VALUES ('2003-03-04_work-plan')
INSERT INTO @LIST_TABLES VALUES ('2003-06-25_schedule-essentials-table')
INSERT INTO @LIST_TABLES VALUES ('2008-03-08_Specs-vs-WIs')
INSERT INTO @LIST_TABLES VALUES ('2004-01-15_WID-history')
INSERT INTO @LIST_TABLES VALUES ('2005-06-15_TSGs')
INSERT INTO @LIST_TABLES VALUES ('2006-01-08_WI-rapporteurs')
INSERT INTO @LIST_TABLES VALUES ('2006-03-17_tdocs')
INSERT INTO @LIST_TABLES VALUES ('2009-06-11_CRs-to-WIs')
INSERT INTO @LIST_TABLES VALUES ('2010-02-08_SpecXRef')
INSERT INTO @LIST_TABLES VALUES ('CR-categories')
INSERT INTO @LIST_TABLES VALUES ('2006-03-17_tdocs')
INSERT INTO @LIST_TABLES VALUES ('cmtee-officers')
INSERT INTO @LIST_TABLES VALUES ('committees')
INSERT INTO @LIST_TABLES VALUES ('CR-categories')
INSERT INTO @LIST_TABLES VALUES ('CR-status-values')
INSERT INTO @LIST_TABLES VALUES ('jmm_spec_series')
INSERT INTO @LIST_TABLES VALUES ('Releases')
INSERT INTO @LIST_TABLES VALUES ('Specs_GSM+3G')
INSERT INTO @LIST_TABLES VALUES ('Specs_GSM+3G_release-info')
INSERT INTO @LIST_TABLES VALUES ('List_of_GSM_&_3G_CRs')
INSERT INTO @LIST_TABLES VALUES ('wpm_spec-release_mapping')
INSERT INTO @LIST_TABLES VALUES ('plenary-meetings-with-end-dates')
INSERT INTO @LIST_TABLES VALUES ('LSs_importedSnapshot')

--for each table to import
WHILE (EXISTS(SELECT TOP 1 * FROM @LIST_TABLES))
BEGIN

	--get the table name
	SELECT TOP 1 @CURRENT_TABLE_NAME = TABLE_NAME FROM @LIST_TABLES
	
	--drop it if the table already exists (can be removed if you don't want it)
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[' + @CURRENT_TABLE_NAME + ']') AND type in (N'U'))
		EXEC('DROP TABLE [dbo].[' + @CURRENT_TABLE_NAME + ']')
	
	PRINT 'Table ''' + @CURRENT_TABLE_NAME + ''' dropped.'
	
	-- Creation of table and import data
	SET @CMD = 'SELECT * into [' + @CURRENT_TABLE_NAME + '] FROM OPENDATASOURCE(''Microsoft.ACE.OLEDB.12.0'', ''Data Source="D:\tmp\3GPP_db\Latest\status_smg_3GPP.mdb"'')...[' + @CURRENT_TABLE_NAME + ']'
	EXEC(@CMD)
	
	PRINT 'Table ''' + @CURRENT_TABLE_NAME + ''' Created.'
	
	--SET @CMD = 'TRUNCATE TABLE ['+@CURRENT_TABLE_NAME+']'
	--EXEC(@CMD)
	
	PRINT 'Table ''' + @CURRENT_TABLE_NAME + ''' Truncated.'
	
	SET @CMD = 'ALTER TABLE ['+@CURRENT_TABLE_NAME+'] ADD [Row_id] [int] IDENTITY(1,1) NOT NULL'
	EXEC(@CMD)
	
	
	
	SET @CMD = 'ALTER TABLE ['+@CURRENT_TABLE_NAME+'] ADD CONSTRAINT ['+@CURRENT_TABLE_NAME+'_id] PRIMARY KEY CLUSTERED 
	(
		[Row_id] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]'
	EXEC(@CMD)
	
	PRINT 'Table ''' + @CURRENT_TABLE_NAME + ''' Modified.'

	PRINT 'Table ''' + @CURRENT_TABLE_NAME + ''' imported.'
	
	-- Delete from tables to import		
	DELETE FROM @LIST_TABLES WHERE TABLE_NAME = @CURRENT_TABLE_NAME
END