//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Community
    {
        public int TbId { get; set; }
        public string TbName { get; set; }
        public Nullable<int> ParentTbId { get; set; }
        public string ShortName { get; set; }
        public string ActiveCode { get; set; }
    }
}
