//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Enum_ChangeRequestStatus
    {
        public int Pk_EnumChangeRequestStatus { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    
        public Enum_EntityStatus EntityStatus { get; set; }
    }
}
