//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Enum_ChangeRequestStatus
    {
        public Enum_ChangeRequestStatus()
        {
            this.ChangeRequests = new HashSet<ChangeRequest>();
            this.ChangeRequestTsgDatas = new HashSet<ChangeRequestTsgData>();
        }
    
        public int Pk_EnumChangeRequestStatus { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ChangeRequest> ChangeRequests { get; set; }
        public virtual ICollection<ChangeRequestTsgData> ChangeRequestTsgDatas { get; set; }
    
        public Enum_EntityStatus EntityStatus { get; set; }
    }
}
