//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Enum_TDocStatus
    {
        public Enum_TDocStatus()
        {
            this.ChangeRequests = new HashSet<ChangeRequest>();
            this.ChangeRequests1 = new HashSet<ChangeRequest>();
        }
    
        public int Pk_EnumTDocStatus { get; set; }
        public int SortOrder { get; set; }
        public bool WGUsable { get; set; }
        public bool TSGUsable { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ChangeRequest> ChangeRequests { get; set; }
        public virtual ICollection<ChangeRequest> ChangeRequests1 { get; set; }
    
        public Enum_EntityStatus EntityStatus { get; set; }
    }
}
