//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Enum_TDocStatus
    {
        public Enum_TDocStatus()
        {
            this.ChangeRequests = new HashSet<ChangeRequest>();
            this.ChangeRequests1 = new HashSet<ChangeRequest>();
        }
    
        public int Pk_EnumTDocStatus { get; set; }
        public int SortOrder { get; set; }
        public bool WGUsable { get; set; }
        public bool TSGUsable { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ChangeRequest> ChangeRequests { get; set; }
        public virtual ICollection<ChangeRequest> ChangeRequests1 { get; set; }
    
        public Enum_EntityStatus EntityStatus { get; set; }
    }
}
