//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Enum_Technology
    {
        public Enum_Technology()
        {
            this.SpecificationTechnologies = new HashSet<SpecificationTechnology>();
        }
    
        public int Pk_Enum_TechnologyId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<int> WpmProjectId { get; set; }
    
        public virtual ICollection<SpecificationTechnology> SpecificationTechnologies { get; set; }
    
        public Enum_EntityStatus EntityStatus { get; set; }
    }
}
