//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class LatestFolder
    {
        public int Pk_LatestFolderId { get; set; }
        public string FolderName { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string UserName { get; set; }
    
        public Enum_EntityStatus EntityStatus { get; set; }
    }
}
