//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remark
    {
        public int Pk_RemarkId { get; set; }
        public Nullable<int> Fk_ReleaseId { get; set; }
        public Nullable<int> Fk_PersonId { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string RemarkText { get; set; }
        public string PersonName { get; set; }
    
        public virtual Release Release { get; set; }
    }
}
