//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Specification
    {
        public Specification()
        {
            this.Histories = new HashSet<History>();
            this.Remarks = new HashSet<Remark>();
            this.Specification_WorkItem = new HashSet<Specification_WorkItem>();
            this.SpecificationRapporteurs = new HashSet<SpecificationRapporteur>();
            this.Specification_Release = new HashSet<Specification_Release>();
            this.SpecificationTechnologies = new HashSet<SpecificationTechnology>();
            this.SpecificationResponsibleGroups = new HashSet<SpecificationResponsibleGroup>();
            this.SpecificationChilds = new HashSet<Specification>();
            this.SpecificationParents = new HashSet<Specification>();
            this.Versions = new HashSet<Version>();
        }
    
        public int Pk_SpecificationId { get; set; }
        public string Number { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsUnderChangeControl { get; set; }
        public Nullable<bool> promoteInhibited { get; set; }
        public Nullable<bool> IsForPublication { get; set; }
        public string Title { get; set; }
        public Nullable<bool> ComIMS { get; set; }
        public Nullable<bool> EPS { get; set; }
        public Nullable<bool> C_2gCommon { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> TitleVerified { get; set; }
        public string URL { get; set; }
        public string ITU_Description { get; set; }
        public Nullable<int> Fk_SerieId { get; set; }
        public Nullable<bool> IsTS { get; set; }
        public Nullable<System.DateTime> MOD_TS { get; set; }
        public string MOD_BY { get; set; }
    
        public virtual Enum_Serie Enum_Serie { get; set; }
        public virtual ICollection<History> Histories { get; set; }
        public virtual ICollection<Remark> Remarks { get; set; }
        public virtual ICollection<Specification_WorkItem> Specification_WorkItem { get; set; }
        public virtual ICollection<SpecificationRapporteur> SpecificationRapporteurs { get; set; }
        public virtual ICollection<Specification_Release> Specification_Release { get; set; }
        public virtual ICollection<SpecificationTechnology> SpecificationTechnologies { get; set; }
        public virtual ICollection<SpecificationResponsibleGroup> SpecificationResponsibleGroups { get; set; }
        public virtual ICollection<Specification> SpecificationChilds { get; set; }
        public virtual ICollection<Specification> SpecificationParents { get; set; }
        public virtual ICollection<Version> Versions { get; set; }
    
        public Enum_EntityStatus EntityStatus { get; set; }
    }
}
