//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Specification_WorkItem
    {
        public int Pk_Specification_WorkItemId { get; set; }
        public int Fk_SpecificationId { get; set; }
        public int Fk_WorkItemId { get; set; }
        public Nullable<bool> isPrime { get; set; }
        public Nullable<bool> IsSetByUser { get; set; }
    
        public virtual Specification Specification { get; set; }
        public virtual WorkItem WorkItem { get; set; }
    
        public Enum_EntityStatus EntityStatus { get; set; }
    }
}
