//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class SyncInfo
    {
        public int Pk_SyncId { get; set; }
        public string TerminalName { get; set; }
        public int Offline_PK_Id { get; set; }
        public Nullable<int> Fk_VersionId { get; set; }
        public Nullable<int> Fk_RemarkId { get; set; }
    
        public virtual SpecVersion Version { get; set; }
        public virtual Remark Remark { get; set; }
    
        public Enum_EntityStatus EntityStatus { get; set; }
    }
}
