//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Users_Groups
    {
        public int PERSON_ID { get; set; }
        public int PLIST_ID { get; set; }
        public Nullable<int> TB_ID { get; set; }
        public string PERS_ROLE_CODE { get; set; }
    }
}
