//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Users_AdHoc_Roles
    {
        public int UserID { get; set; }
        public string PERSON_ID { get; set; }
        public string RoleName { get; set; }
    
        public Enum_EntityStatus EntityStatus { get; set; }
    }
}
