//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class View_ContributionsWithAditionnalData
    {
        public int pk_Contribution { get; set; }
        public string uid { get; set; }
        public int fk_SpecificationId { get; set; }
        public Nullable<int> Specification_MajorVersion { get; set; }
        public Nullable<int> Specification_TechnicalVersion { get; set; }
        public Nullable<int> Specification_EditorialVersion { get; set; }
    
        public Enum_EntityStatus EntityStatus { get; set; }
    }
}
