//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class WorkItem
    {
        public WorkItem()
        {
            this.Remarks = new HashSet<Remark>();
            this.ChildWis = new HashSet<WorkItem>();
            this.WorkItems_ResponsibleGroups = new HashSet<WorkItems_ResponsibleGroups>();
        }
    
        public int Pk_WorkItemUid { get; set; }
        public Nullable<int> WorkplanId { get; set; }
        public string Name { get; set; }
        public string Acronym { get; set; }
        public Nullable<int> WiLevel { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Completion { get; set; }
        public Nullable<System.DateTime> LastModification { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> Fk_ParentWiId { get; set; }
        public Nullable<int> Fk_ReleaseId { get; set; }
        public string Wid { get; set; }
        public Nullable<int> RapporteurId { get; set; }
        public string RapporteurStr { get; set; }
        public Nullable<int> TsgApprovalMtgId { get; set; }
        public string TsgApprovalMtgRef { get; set; }
        public Nullable<int> PcgApprovalMtgId { get; set; }
        public string PcgApprovalMtgRef { get; set; }
        public Nullable<int> TsgStoppedMtgId { get; set; }
        public string TsgStoppedMtgRef { get; set; }
        public Nullable<int> PcgStoppedMtgId { get; set; }
        public string PcgStoppedMtgRef { get; set; }
        public string StatusReport { get; set; }
        public string RapporteurCompany { get; set; }
        public string TssAndTrs { get; set; }
    
        public virtual Release Release { get; set; }
        public virtual ICollection<Remark> Remarks { get; set; }
        public virtual ICollection<WorkItem> ChildWis { get; set; }
        public virtual WorkItem ParentWi { get; set; }
        public virtual ICollection<WorkItems_ResponsibleGroups> WorkItems_ResponsibleGroups { get; set; }
    }
}
