//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class WorkItem
    {
        public WorkItem()
        {
            this.Remarks = new HashSet<Remark>();
            this.ChildWis = new HashSet<WorkItem>();
            this.WorkItems_ResponsibleGroups = new HashSet<WorkItems_ResponsibleGroups>();
            this.Specification_WorkItem = new HashSet<Specification_WorkItem>();
            this.CR_WorkItems = new HashSet<CR_WorkItems>();
        }
    
        public int Pk_WorkItemUid { get; set; }
        public Nullable<int> WorkplanId { get; set; }
        public string Name { get; set; }
        public string Acronym { get; set; }
        public Nullable<int> WiLevel { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Completion { get; set; }
        public Nullable<System.DateTime> LastModification { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> Fk_ParentWiId { get; set; }
        public Nullable<int> Fk_ReleaseId { get; set; }
        public string Wid { get; set; }
        public Nullable<int> RapporteurId { get; set; }
        public string RapporteurStr { get; set; }
        public Nullable<int> TsgApprovalMtgId { get; set; }
        public string TsgApprovalMtgRef { get; set; }
        public Nullable<int> PcgApprovalMtgId { get; set; }
        public string PcgApprovalMtgRef { get; set; }
        public Nullable<int> TsgStoppedMtgId { get; set; }
        public string TsgStoppedMtgRef { get; set; }
        public Nullable<int> PcgStoppedMtgId { get; set; }
        public string PcgStoppedMtgRef { get; set; }
        public string StatusReport { get; set; }
        public string RapporteurCompany { get; set; }
        public string TssAndTrs { get; set; }
        public string Effective_Acronym { get; set; }
    
        public virtual Release Release { get; set; }
        public virtual ICollection<Remark> Remarks { get; set; }
        public virtual ICollection<WorkItem> ChildWis { get; set; }
        public virtual WorkItem ParentWi { get; set; }
        public virtual ICollection<WorkItems_ResponsibleGroups> WorkItems_ResponsibleGroups { get; set; }
        public virtual ICollection<Specification_WorkItem> Specification_WorkItem { get; set; }
        public virtual ICollection<CR_WorkItems> CR_WorkItems { get; set; }
    
        public Enum_EntityStatus EntityStatus { get; set; }
    }
}
