//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.UserRights.DSDBDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_IN_LIST
    {
        public int PLIST_ID { get; set; }
        public int PERSON_ID { get; set; }
        public string PERS_ROLE_CODE { get; set; }
        public System.DateTime START_DATE { get; set; }
        public string FREE_TEXT { get; set; }
        public string INVITATION_SENT_FLG { get; set; }
        public Nullable<System.DateTime> INVITATION_DATE { get; set; }
        public string CONFIRMATION_FLG { get; set; }
        public Nullable<System.DateTime> CONFIRMATION_DATE { get; set; }
        public string PARTICIPATION_FLG { get; set; }
        public string DOC_REQUESTED_FLG { get; set; }
        public Nullable<System.DateTime> DOC_REQUESTED_DATE { get; set; }
        public string DOC_SENT_FLG { get; set; }
        public Nullable<System.DateTime> DOC_SENT_DATE { get; set; }
        public Nullable<int> LINE_POSITION { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public int ORGA_ID { get; set; }
        public string REPRESENT_FLG { get; set; }
        public string PARTICIPANT_ACCESS { get; set; }
        public string OFFICIAL_ACCESS { get; set; }
        public System.DateTime MOD_TS { get; set; }
        public string MOD_BY { get; set; }
        public string no_dispatch_flg { get; set; }
        public string USE_PAPER_FLG { get; set; }
        public string WEB_MOD_BY { get; set; }
        public Nullable<System.DateTime> WEB_MOD_TS { get; set; }
        public Nullable<int> REPRESENT_ORGA_ID { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual PERSON_LIST PERSON_LIST { get; set; }
    }
}
