//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncInterface.DataContract
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    public class ChangeRequest
    {
        [DataMember]
        public int Pk_ChangeRequest { get; set; }
        [DataMember]
        public string CRNumber { get; set; }
        [DataMember]
        public Nullable<int> Revision { get; set; }
        [DataMember]
        public string Subject { get; set; }
        [DataMember]
        public Nullable<int> Fk_TSGStatus { get; set; }
        [DataMember]
        public Nullable<int> Fk_WGStatus { get; set; }
        [DataMember]
        public Nullable<System.DateTime> CreationDate { get; set; }
        [DataMember]
        public string TSGSourceOrganizations { get; set; }
        [DataMember]
        public string WGSourceOrganizations { get; set; }
        [DataMember]
        public Nullable<int> TSGMeeting { get; set; }
        [DataMember]
        public Nullable<int> TSGTarget { get; set; }
        [DataMember]
        public Nullable<int> WGSourceForTSG { get; set; }
        [DataMember]
        public Nullable<int> Fk_TSGTDoc { get; set; }
        [DataMember]
        public Nullable<int> WGMeeting { get; set; }
        [DataMember]
        public Nullable<int> WGTarget { get; set; }
        [DataMember]
        public Nullable<int> Fk_WGTDoc { get; set; }
        [DataMember]
        public Nullable<int> Fk_Enum_CRCategory { get; set; }
        [DataMember]
        public int Fk_SpecRelease { get; set; }
        [DataMember]
        public int Fk_Versions { get; set; }
    }
}
