//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncInterface.DataContract
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    public class ResponsibleGroup_Secretary
    {
        [DataMember]
        public Nullable<int> TbId { get; set; }
        [DataMember]
        public string Email { get; set; }
        [DataMember]
        public int PersonId { get; set; }
    }
}
