//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncInterface.DataContract
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    public class Specification
    {
        [DataMember]
        public int Pk_SpecificationId { get; set; }
        [DataMember]
        public string Number { get; set; }
        [DataMember]
        public bool IsActive { get; set; }
        [DataMember]
        public Nullable<bool> IsUnderChangeControl { get; set; }
        [DataMember]
        public Nullable<bool> promoteInhibited { get; set; }
        [DataMember]
        public Nullable<bool> IsForPublication { get; set; }
        [DataMember]
        public string Title { get; set; }
        [DataMember]
        public Nullable<bool> ComIMS { get; set; }
        [DataMember]
        public Nullable<bool> EPS { get; set; }
        [DataMember]
        public Nullable<bool> C_2gCommon { get; set; }
        [DataMember]
        public Nullable<System.DateTime> CreationDate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> TitleVerified { get; set; }
        [DataMember]
        public string URL { get; set; }
        [DataMember]
        public string ITU_Description { get; set; }
        [DataMember]
        public Nullable<int> Fk_SerieId { get; set; }
        [DataMember]
        public Nullable<bool> IsTS { get; set; }
        [DataMember]
        public Nullable<System.DateTime> MOD_TS { get; set; }
        [DataMember]
        public string MOD_BY { get; set; }
    }
}
