//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncInterface.DataContract
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    public class SpecificationResponsibleGroup
    {
        [DataMember]
        public int Pk_SpecificationResponsibleGroupId { get; set; }
        [DataMember]
        public int Fk_SpecificationId { get; set; }
        [DataMember]
        public int Fk_commityId { get; set; }
        [DataMember]
        public bool IsPrime { get; set; }
    }
}
