//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncInterface.DataContract
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    public class View_ModulesPages
    {
        [DataMember]
        public string TabName { get; set; }
        [DataMember]
        public string TabPath { get; set; }
        [DataMember]
        public int ModuleID { get; set; }
        [DataMember]
        public int TabID { get; set; }
    }
}
