//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncInterface.DataContract
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    public class WorkItem
    {
        [DataMember]
        public int Pk_WorkItemUid { get; set; }
        [DataMember]
        public Nullable<int> WorkplanId { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public string Acronym { get; set; }
        [DataMember]
        public Nullable<int> WiLevel { get; set; }
        [DataMember]
        public Nullable<System.DateTime> StartDate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> EndDate { get; set; }
        [DataMember]
        public Nullable<int> Completion { get; set; }
        [DataMember]
        public Nullable<System.DateTime> LastModification { get; set; }
        [DataMember]
        public Nullable<System.DateTime> CreationDate { get; set; }
        [DataMember]
        public Nullable<int> Fk_ParentWiId { get; set; }
        [DataMember]
        public Nullable<int> Fk_ReleaseId { get; set; }
        [DataMember]
        public string Wid { get; set; }
        [DataMember]
        public Nullable<int> RapporteurId { get; set; }
        [DataMember]
        public string RapporteurStr { get; set; }
        [DataMember]
        public Nullable<int> TsgApprovalMtgId { get; set; }
        [DataMember]
        public string TsgApprovalMtgRef { get; set; }
        [DataMember]
        public Nullable<int> PcgApprovalMtgId { get; set; }
        [DataMember]
        public string PcgApprovalMtgRef { get; set; }
        [DataMember]
        public Nullable<int> TsgStoppedMtgId { get; set; }
        [DataMember]
        public string TsgStoppedMtgRef { get; set; }
        [DataMember]
        public Nullable<int> PcgStoppedMtgId { get; set; }
        [DataMember]
        public string PcgStoppedMtgRef { get; set; }
        [DataMember]
        public string StatusReport { get; set; }
        [DataMember]
        public string RapporteurCompany { get; set; }
        [DataMember]
        public string TssAndTrs { get; set; }
    }
}
