//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncInterface.DataContract
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    public class WorkItems_ResponsibleGroups
    {
        [DataMember]
        public int Pk_WorkItemResponsibleGroups { get; set; }
        [DataMember]
        public Nullable<int> Fk_WorkItemId { get; set; }
        [DataMember]
        public Nullable<int> Fk_TbId { get; set; }
        [DataMember]
        public string ResponsibleGroup { get; set; }
        [DataMember]
        public Nullable<bool> IsPrimeResponsible { get; set; }
    }
}
