//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Business.UserRightsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonRights", Namespace="http://schemas.datacontract.org/2004/07/Etsi.UserRights.Interface")]
    [System.SerializableAttribute()]
    public partial class PersonRights : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> ApplicationRightsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.List<string>> CommitteeRightsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> ApplicationRights {
            get {
                return this.ApplicationRightsField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationRightsField, value) != true)) {
                    this.ApplicationRightsField = value;
                    this.RaisePropertyChanged("ApplicationRights");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.List<string>> CommitteeRights {
            get {
                return this.CommitteeRightsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommitteeRightsField, value) != true)) {
                    this.CommitteeRightsField = value;
                    this.RaisePropertyChanged("CommitteeRights");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserRightsService.IUserRightsService")]
    public interface IUserRightsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRightsService/GetRights", ReplyAction="http://tempuri.org/IUserRightsService/GetRightsResponse")]
        Etsi.Ultimate.Business.UserRightsService.PersonRights GetRights(int personId, string portal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserRightsServiceChannel : Etsi.Ultimate.Business.UserRightsService.IUserRightsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserRightsServiceClient : System.ServiceModel.ClientBase<Etsi.Ultimate.Business.UserRightsService.IUserRightsService>, Etsi.Ultimate.Business.UserRightsService.IUserRightsService {
        
        public UserRightsServiceClient() {
        }
        
        public UserRightsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserRightsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserRightsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserRightsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Etsi.Ultimate.Business.UserRightsService.PersonRights GetRights(int personId, string portal) {
            return base.Channel.GetRights(personId, portal);
        }
    }
}
