USE [master]
GO

/****** Object:  Database [U3GPPDB]    Script Date: 03/13/2014 17:12:09 ******/
CREATE DATABASE [U3GPPDB] ON  PRIMARY 
( NAME = N'3GPPDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\U3GPPDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'3GPPDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\U3GPPDB_1.ldf' , SIZE = 3456KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [U3GPPDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [U3GPPDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [U3GPPDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [U3GPPDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [U3GPPDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [U3GPPDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [U3GPPDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [U3GPPDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [U3GPPDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [U3GPPDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [U3GPPDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [U3GPPDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [U3GPPDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [U3GPPDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [U3GPPDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [U3GPPDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [U3GPPDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [U3GPPDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [U3GPPDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [U3GPPDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [U3GPPDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [U3GPPDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [U3GPPDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [U3GPPDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [U3GPPDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [U3GPPDB] SET  READ_WRITE 
GO

ALTER DATABASE [U3GPPDB] SET RECOVERY FULL 
GO

ALTER DATABASE [U3GPPDB] SET  MULTI_USER 
GO

ALTER DATABASE [U3GPPDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [U3GPPDB] SET DB_CHAINING OFF 
GO

