CREATE VIEW [dbo].[View_Persons]
AS
SELECT p.PERSON_ID, p.VMS_USER as Username, p.INTERNET_ADD as Email, p.LASTNAME, p.FIRSTNAME, o.ORGA_ID, o.ORGA_NAME, o.ORGA_SHORT, p.DELETED_FLG
FROM [$(DSDB)].dbo.PERSON p
INNER JOIN [$(DSDB)].dbo.ORGANISATION o on o.ORGA_ID = p.ORGA_ID