//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etsi.Ultimate.Module.Specifications.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpecificationDetails_aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpecificationDetails_aspx() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Etsi.Ultimate.Module.Specifications.App_LocalResources.SpecificationDetails.aspx", typeof(SpecificationDetails_aspx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Specification-Release.
        /// </summary>
        public static string Button_Delete_SpecRelease_Tooltip_Allowed {
            get {
                return ResourceManager.GetString("Button_Delete_SpecRelease_Tooltip_Allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can not delete Specification-Release because it contains versions.
        /// </summary>
        public static string Button_Delete_SpecRelease_Tooltip_NotAllowed {
            get {
                return ResourceManager.GetString("Button_Delete_SpecRelease_Tooltip_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à System failed to notify the Secretary and Workplan Manager. Please contact them directly to notify them of the reference assignment..
        /// </summary>
        public static string Error_NumberAssigned_NotifyMCC_NoEmail {
            get {
                return ResourceManager.GetString("Error_NumberAssigned_NotifyMCC_NoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specification has been created, but system failed to notify the Specification Manager(s). Please contact them directly to request them to set the number..
        /// </summary>
        public static string Error_NumberNeeded_NotifySpecMgr_NoEmail {
            get {
                return ResourceManager.GetString("Error_NumberNeeded_NotifySpecMgr_NoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A file should be provided..
        /// </summary>
        public static string ITU_Error_NoFileToUpload {
            get {
                return ResourceManager.GetString("ITU_Error_NoFileToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specification has been successfully created. An email has been sent to the Specification Manager(s) requesting the allocation of a specification number..
        /// </summary>
        public static string Warning_NumberNeeded_NotifySpec_Mgr {
            get {
                return ResourceManager.GetString("Warning_NumberNeeded_NotifySpec_Mgr", resourceCulture);
            }
        }
    }
}
