@ECHO OFF

SET BASE_PATH_OFFLINE_SYNC_CLIENT=%1
SET BASE_PATH_TARGET=%2
SET SERVICE_LOGIN=%3
SET SERVICE_PASSWORD=%4

chdir /D %BATCHLOCATION% 
CALL %BATCHLOCATION%\Setups\SyncClient.bat %BASE_PATH_OFFLINE_SYNC_CLIENT% %BASE_PATH_TARGET% %SERVICE_LOGIN% %SERVICE_PASSWORD%