@ECHO OFF

SET BASE_PATH_USERRIGHTS=%1
SET BASE_PATH_REMOTE_CONSENSUS=%2
SET BASE_PATH_VFS_HOST_FTP=%3
SET BASE_PATH_OFFLINE_SYNC_SERVICE=%4
SET BASE_PATH_TARGET=%5
SET SERVICE_LOGIN=%6
SET SERVICE_PASSWORD=%7

chdir /D %BATCHLOCATION% 
CALL %BATCHLOCATION%\Setups\UserRightsService.bat %BASE_PATH_USERRIGHTS% %BASE_PATH_TARGET% %SERVICE_LOGIN% %SERVICE_PASSWORD%
chdir /D %BATCHLOCATION%
CALL %BATCHLOCATION%\Setups\RCService.bat %BASE_PATH_REMOTE_CONSENSUS% %BASE_PATH_TARGET%
chdir /D %BATCHLOCATION%
CALL %BATCHLOCATION%\Setups\HostService.bat %BASE_PATH_VFS_HOST_FTP% %BASE_PATH_TARGET% %SERVICE_LOGIN% %SERVICE_PASSWORD%
chdir /D %BATCHLOCATION%
CALL %BATCHLOCATION%\Setups\VFSService.bat %BASE_PATH_VFS_HOST_FTP% %BASE_PATH_TARGET%
chdir /D %BATCHLOCATION%
CALL %BATCHLOCATION%\Setups\FTPService.bat %BASE_PATH_VFS_HOST_FTP% %BASE_PATH_TARGET%
chdir /D %BATCHLOCATION%
CALL %BATCHLOCATION%\Setups\SyncService.bat %BASE_PATH_OFFLINE_SYNC_SERVICE% %BASE_PATH_TARGET%