@ECHO OFF

SET BASE_PATH_USERRIGHTS=%1
SET BASE_PATH_REMOTE_CONSENSUS=%2
SET BASE_PATH_VFS_HOST_FTP=%3
sET SERVICE_ULTIMATE=%4
SET BASE_PATH_TARGET=%5
SET SERVICE_LOGIN=%6
SET SERVICE_PASSWORD=%7

ECHO @@@ Choose services to reinstall :
ECHO @@@ "u" for UltimateService
ECHO @@@ "r" for UserRightsService
ECHO @@@ -
ECHO @@@ "a" for all the services
SET /P SERVICE_TO_REINSTALL=

IF "%SERVICE_TO_REINSTALL%" == "u" (
	chdir /D %BATCHLOCATION%
	CALL %BATCHLOCATION%\Setups\UltimateService.bat %SERVICE_ULTIMATE% %BASE_PATH_TARGET%
)
IF "%SERVICE_TO_REINSTALL%" == "r" (
	chdir /D %BATCHLOCATION% 
	CALL %BATCHLOCATION%\Setups\UserRightsService.bat %BASE_PATH_USERRIGHTS% %BASE_PATH_TARGET% %SERVICE_LOGIN% %SERVICE_PASSWORD%
) 
IF "%SERVICE_TO_REINSTALL%" == "a" (
	chdir /D %BATCHLOCATION% 
	CALL %BATCHLOCATION%\Setups\UserRightsService.bat %BASE_PATH_USERRIGHTS% %BASE_PATH_TARGET% %SERVICE_LOGIN% %SERVICE_PASSWORD%
	chdir /D %BATCHLOCATION%
	CALL %BATCHLOCATION%\Setups\RCService.bat %BASE_PATH_REMOTE_CONSENSUS% %BASE_PATH_TARGET%
	chdir /D %BATCHLOCATION%
	CALL %BATCHLOCATION%\Setups\HostService.bat %BASE_PATH_VFS_HOST_FTP% %BASE_PATH_TARGET% %SERVICE_LOGIN% %SERVICE_PASSWORD%
	chdir /D %BATCHLOCATION%
	CALL %BATCHLOCATION%\Setups\VFSService.bat %BASE_PATH_VFS_HOST_FTP% %BASE_PATH_TARGET%
	chdir /D %BATCHLOCATION%
	CALL %BATCHLOCATION%\Setups\FTPService.bat %BASE_PATH_VFS_HOST_FTP% %BASE_PATH_TARGET%
	chdir /D %BATCHLOCATION%
	CALL %BATCHLOCATION%\Setups\UltimateService.bat %SERVICE_ULTIMATE% %BASE_PATH_TARGET%
)ELSE (
	ECHO No service installed.
)